apiVersion: skaffold/v4beta1
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: eabasguliyev/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: eabasguliyev/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: eabasguliyev/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: eabasguliyev/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
