apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: eabasguliyev/orders
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://orders-mongo-srv:27017/orders"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      initContainers:
        - name: init-services
          image: busybox
          command:
            [
              "sh",
              "-c",
              "namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace);",
              "serviceName=nats-srv",
              "until nc -z $serviceName.$namespace.svc.cluster.local 4222;",
              "do echo waiting for $serviceName;",
              "sleep 2;",
              "done;",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  type: ClusterIP #default
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
