apiVersion: v1
kind: Service
metadata:
  name: comments-nodeport-srv
spec:
  selector:
    app: comments
  type: NodePort
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
